### ISSUE TITLE
shared storage volume for Prometheus

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-iam/eks-configuration#4]
Hey @The-smooth-operator,

I would like to adjust our configuration to use an EBS volume for shared storage. What do you think?

https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md

If I'm understanding the current configuration correctly, it sounds like Prometheus scrapes metrics and stores them in memory and on disk in the pod. If the pod(s) die, would we lose all history?

**Comment by The-smooth-operator** [comment]
hey Daniel, that's absolutely right: there's not persistent storage configured yet.
I think adding an EBS is needed once we want to store metrics, until now was ok with this setup because these metrics are just for a POC.

I think the trickiest part of adding the volume is to calculate space+IO throughput needed. Based on my experience the storage needs to be reasonably fast in order to make browsing graphs in Grafana a nice experience, and also to avoid Prometheus throttling.

But we can just start with whatever and keep measuring how it does in terms of performance. After we could also make a kind of stress-test where we launch many pods and let Prometheus scrape them to see how the storage behaves.
